### ISSUE TITLE
Excessive logging

### ISSUE THREAD

**Issue by janvda** [yayadrian/node-red-slack#16]
Hi,

This node is logging a lot in the node red log file.

1/ When sending a single message to the [Slack Bot Out] node it is logging 3 lines.  E.g.: 

> 31 Jan 23:31:54 - [info] [Slack Bot Out:stemija slackbot response] {"payload":<deleted part of json message that is spanning 2 lines>}}}
> 31 Jan 23:31:54 - [info] [Slack Bot Out:stemija slackbot response] Getting slackChannel () from slackObj in message.
> 31 Jan 23:31:54 - [info] [Slack Bot Out:stemija slackbot response] object

2/ When sending a message to the [Slack] node:  it becomes also logged as a line in the node red. E.g.:

> 31 Jan 23:30:12 - [info] [Slack Bot Out:stemija slackbot response] {"payload":"<deleted par of json message that is spanning 3 lines>}}}

I would not expect these kind of messages in the node red log file.
If all my nodes that are sending messages to external systems would log these messages then my log file would be filled with thousands of those messages every day.

kr
jan

**Comment by yayadrian** [comment]
Closing this issue as it is resolved in version 2.0.0
