### ISSUE TITLE
Unexpected messages are logged at startup

### ISSUE THREAD

**Issue by janvda** [yayadrian/node-red-slack#17]
Hi

When I restart node-red then it is logging several messages related to the [Slack Bot In] and [Slack Bot Out] which are a bit concerning.
E.g. 

> Welcome to Node-RED
> ===================
> 31 Jan 23:57:03 - [info] Node-RED version: v0.17.5
> 31 Jan 23:57:03 - [info] Node.js  version: v4.8.4
> 31 Jan 23:57:03 - [info] Linux 4.9.24-v7+ arm LE
> 31 Jan 23:57:04 - [info] Loading palette nodes
> 31 Jan 23:57:09 - [info] Dashboard version 2.6.1 started at /ui
> 31 Jan 23:57:17 - [info] Settings file  : /home/pi/.node-red/settings.js
> 31 Jan 23:57:17 - [info] User directory : /home/pi/.node-red
> 31 Jan 23:57:17 - [info] Flows file     : /home/pi/.node-red/flows_pi3one.json
> 31 Jan 23:57:17 - [info] Server now running at http://127.0.0.1:1880/
> 31 Jan 23:57:18 - [info] Starting flows
> 31 Jan 23:57:21 - [info] [Slack Bot In:stemija slackbot] IN: new slack session
> **31 Jan 23:57:21 - [info] [Slack Bot In:stemija slackbot] Slack not connected**
> **[Wed Jan 31 2018 23:57:21 GMT+0100 (CET)] INFO Connecting...**
> **31 Jan 23:57:21 - [info] [Slack Bot Out:stemija slackbot response] OUT: using an old slack session**
> **31 Jan 23:57:21 - [info] [Slack Bot Out:stemija slackbot response] Slack already connected**
> 31 Jan 23:57:29 - [warn] [google-credentials:6e76318c.44294] trying to refresh token due to expiry
> 31 Jan 23:57:30 - [info] Started flows
> 31 Jan 23:57:30 - [info] [slack:#cv channel] {[deleted part json msg]}
> ...
> 31 Jan 23:57:30 - [info] [mqtt-broker:9c9ae2bc.63652] Connected to broker: mqtt://192.168.1.131:1883
> **31 Jan 23:57:30 - [info] [Slack Bot In:stemija slackbot] in: Logged in:**
> **31 Jan 23:57:31 - [info] [Slack Bot In:stemija slackbot] Slack already connected**
> **31 Jan 23:57:31 - [info] [Slack Bot Out:stemija slackbot response] Slack already connected**
 
Especially the last 2 messages are strange.  Why is it saying that it is already connected ?

For each connection, I would expect a single message like it is done for the mqtt-broker (see above).

kr
Jan

**Comment by travisghansen** [comment]
Resolved by `2.0.0`.
