### ISSUE TITLE
Slack bot in/out nodes do not have default label names

### ISSUE THREAD

**Issue by annaet** [yayadrian/node-red-slack#20]
The slack bot in/out nodes do not have default label names as the general slack node does.

The labels are set to either the node name or the empty string using the below code in [slackpost.html](https://github.com/yayadrian/node-red-slack/blob/master/slackpost.html).

```
label: function() {
    return this.name||"";
},
```

This means that when the node is dragged onto the node-red workspace it is unnamed and it's hard to know what node it is unless you recognise the slack logo.

I'm happy to create a PR for this change.

**Comment by yayadrian** [comment]
Thanks for raising @annaet 
If you could create a PR that would be awesome. 
Otherwise I'll try to take a look into this soon.

**Comment by travisghansen** [comment]
Resolved by `2.0.0`.
