### ISSUE TITLE
keeps complaining about Slack Bot Out

### ISSUE THREAD

**Issue by realjax** [yayadrian/node-red-slack#23]
Hi,

Couldn't be bothered with the migration so I uninstalled. However, node-red keeps complaining about missing nodes type Slack bot out. 
There are no configs anymore, no more nodes that use it, yet it keeps complaining.
How do I fix this?

**Comment by realjax** [comment]
Never mind, had to manually remove an instance from the flows.json in order to fix it.

**Comment by travisghansen** [comment]
@realjax yeah Node-RED can be funny about that, usually pretty easy to find them and delete.  Alternatively, you could simply pin the old package version with npm and leave it as it was.
