### ISSUE TITLE
Multiple workspaces bot

### ISSUE THREAD

**Issue by JbIPS** [yayadrian/node-red-slack#26]
Hi,

I'm trying to create a bot that will be installed on multiple workspaces, thus having multiple tokens. From what I saw in the config and in the code, the client is created very early and cannot be set on a per-message basis. Am I right?

Here's my usecase:
* I get an HTTP input from a user with a payload containing a message and a workspace token
* a function node setup an object with the Slack payload and credentials
* slack-web-out reads the credentials, create the client and send the message.

Is this doable right now? Should I suggest a PR to allow such behavior?

Thank you for your help

**Comment by travisghansen** [comment]
Interesting. Right now each config is static and has to be configured and deployed before usage.

Given your use case a simple http request node should be sufficient. It would be pretty easy to create without using the slack node at all.

Does that sound doable or am I missing something else? I can provide some tips on how to create that node if you'd like...

**Comment by JbIPS** [comment]
You mean not using your Slack node but just creating the request manually?

**Comment by travisghansen** [comment]
Yeah..

**Comment by JbIPS** [comment]
That seams doable but I'm always trying first to add features to an existing libraries before creating a new one.

But if you think here is not the place I'll do it from scratch. Otherwise I'm more than welcome to contribute :wink:

**Comment by travisghansen** [comment]
Yeah this node actually stores the tokens encrypted etc. Not only that these nodes maintain state on the connections such as what rooms there are, who's logged in, etc etc. It's truly meant to be a long-term connected bot (even the web node as odd as that sounds).

Your use-case of being ephemeral to Node-RED doesn't really fit the existing stuff :(

**Comment by JbIPS** [comment]
I understand 😃. 

Thank you for your help
