### ISSUE TITLE
Error stopping node: Close timed out when deploying

### ISSUE THREAD

**Issue by PaulWieland** [yayadrian/node-red-slack#27]
When trying to deploy a new `slack-web-out` with a new configuration (I added my bot token), the node-red deploy hangs for a few seconds and then `"Error stopping node: Close timed out"` is displayed in the debug console.

I am behind a corporate proxy. I configured the proxy for both http and https and tested it with this in a function node, which works:

```javascript
let require = global.get('require');
let request = require('request');


request('https://google.com', { json: true }, (err, res, body) => {
  if (err) { return node.error(err) }
  node.warn(res);
  node.warn(body);
});
```

Any ideas?

**Comment by travisghansen** [comment]
So you've added a new configuration *and* a `slack-web-out` at the same time and hit the deploy button? After the very first time does it exhibit the same issue?

**Comment by PaulWieland** [comment]
Every time I deploy, it hangs for a few seconds and then I get the error. I also should mention that the `slack-web-out` node shows disconnected.

**Comment by travisghansen** [comment]
Ah, it stays disconnected the whole time? It never shows connected?

**Comment by PaulWieland** [comment]
Correct. I haven’t gotten it to connect at all.

**Comment by travisghansen** [comment]
OK, I've got some code queued up that I think will fix this. Now on to the bigger issue, why isn't it connecting? Can you send over the first portion of your token?

**Comment by PaulWieland** [comment]
Do you just mean the prefix?

`xoxb-101899299508`

Let me know if you have something you want me to try in order to isolate why it's not connecting. 
Do you have an example get/post `request` I could try outside of node-red to try and debug it?

I think it should be able to communicate via https, but I had to do some weird things to make the proxy work.

**Comment by travisghansen** [comment]
`xoxb-` should generally be good. The connection state in the ui is based on the websocket connection. It's not terribly difficult to replicate the http request but it's generally hidden by the sdk this project is based on.

You can use an http node in Node-RED and follow the instructions here: https://api.slack.com/web

It's quite straight forward really and shouldn't take much to replicate a simple http method.

**Comment by steeef** [comment]
I've just upgraded from `0.1.2` and run into this issue as well. I followed the instructions to add a function from the migration section of the README, as I'm just trying to do a simple `slack web out` node.

I created a new Slack app with OAuth scope `chat:write:bot` and verified the token I'm using in node-red matches.

Watching node-red's logs, I see this when attempting a deploy:

```
Nov 29 09:30:40 avi docker[27347]: [INFO]  @slack/client:RTMClient:15 unable to RTM start: An API error occurred: missing_scope
```

Let me know if you need any more information.

**Comment by travisghansen** [comment]
@steeef I don't think you gave it enough permissions. Is it a 'bot' token? That error message is suggesting the token doesn't have enough permissions to connect to the real-time messaging (ie: websocket) service.

**Comment by steeef** [comment]
I guess that's where I'm stuck. I've only given it `chat:write:bot`, as all I want to do is to be able to call `postMessage` as the bot user. Reviewing OAuth scope documentation, I can't see what else I'd need to add.

**Comment by travisghansen** [comment]
@steeef yeah, the package/node does much much more than that now. If literally all you want to is send a message via http **AND** you can't/don't want to use a bot token, I'd suggest simply using an http node (it's quite trivial to do so to achieve your particular goal as I understand it).

Let me know, happy to help draft that up if that's the way you want to go.

**Comment by travisghansen** [comment]
#25 is related as well I'd guess.

**Comment by steeef** [comment]
Yeah, and http request node is what I was looking for. I've got some ideas for using Slack in other ways, but for now just using an incoming webhook works for me. Thanks for the tip!

**Comment by travisghansen** [comment]
Yeah ok. The updated version of this node basically does everything you could want to do with slack now. It real-time listens for messages, status changes, typing notifications etc. It's a full blown client essentially.
