### ISSUE TITLE
@slack/client no longer supported

### ISSUE THREAD

**Issue by quimnut** [yayadrian/node-red-slack#30]
404's now.

Seems only @slack/rtm-api now.

**Comment by travisghansen** [comment]
You mean npm gives a 404?

**Comment by quimnut** [comment]
API throws 404.
[ERROR]  @slack/client:RTMClient:3 A websocket error occurred: Unexpected server response: 404

**Comment by travisghansen** [comment]
This sounds like an issue perhaps with a proxy or something of that nature in your environment? I've got several instances of the `Node` running from many different location and all are connecting without issue..

**Comment by quimnut** [comment]
I usually run the official nodered container so I built a vm to debug here in Australia with no luck before posting. I also asked slack.

Built a vultr vm in USA/LA just then and it works.

Mar 27 00:44:55 guest node-red.node-red[2197]: [INFO]  @slack/client:WebClient:1 API Call failed due to rate limiting. Will retry in 60 seconds.
Mar 27 00:45:55 guest node-red.node-red[2197]: [WARN]  @slack/client:WebClient:1 http request failed A rate limit was exceeded.
Mar 27 00:46:01 guest node-red.node-red[2197]: 27 Mar 00:46:01 - [info] [slack-config:test] connected to slack with token: xoxb-115...91t


OK made a vultr instance in Sydney and 404.

Mar 27 00:53:03 guest node-red.node-red[2178]: [ERROR]  @slack/client:RTMClient:3 A websocket error occurred: Unexpected server response: 404
Mar 27 00:53:03 guest node-red.node-red[2178]: 27 Mar 00:53:03 - [info] [slack-config:test] disconnected from slack with token: xoxb-115...91t
Mar 27 00:53:03 guest node-red.node-red[2178]: [INFO]  @slack/client:WebClient:1 API Call failed due to rate limiting. Will retry in 60 seconds.

I'll get back to the guys at slack.

**Comment by travisghansen** [comment]
Ok cool let me know.

**Comment by quimnut** [comment]
Slack confirmed the problem was on their end, thanks!
